_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: ""
  MASK_ON: True
  RESNETS:
    DEPTH: 18
  ROI_HEADS:
    NUM_CLASSES: 1

SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.001                   # 総学習率（Warmup 後の最終値）
  MAX_ITER: 52905                 # 総ステップ数 = 14,108 x 15 ÷ 4

  # ---- Warmup 設定 ----
  WARMUP_ITERS: 1000              # 最初の1000ステップで線形にLRを上げていく
  WARMUP_METHOD: "linear"         # 線形増加
  WARMUP_FACTOR: 1.0e-3           # 初期LR = BASE_LR × 0.001 = 0.001 × 0.001 = 1e-6

  # ---- LR Scheduler ----
  STEPS: (35000, 47000)           # 学習率を下げるタイミング（70%と90%あたり）
  GAMMA: 0.1                      # 学習率を1/10に減衰

  # ---- その他 ----
  CHECKPOINT_PERIOD: 1000        # 1000イテレーションごとにモデル保存

INPUT:
  MIN_SIZE_TRAIN: (1080,)
  MAX_SIZE_TRAIN: 1920

DATASETS:
  TRAIN: ("carplate_train",)
  TEST: ("carplate_val",)

TEST:
  EVAL_PERIOD: 500

OUTPUT_DIR: "./output/carplate-maskrcnn-R18"
